# Generated by Django 4.2.27 on 2026-01-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_logpoddiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='estoque',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estoque_da_empresa', to='api.empresa'),
        ),
        migrations.AddField(
            model_name='venda',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendas_da_empresa', to='api.empresa'),
        ),
    ]
