# Generated by Django 4.2.27 on 2026-01-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_lesson_delete_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['priority', 'status', 'data_conclusao_prevista']},
        ),
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='priority',
            field=models.CharField(choices=[('Máxima', 'Máxima'), ('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], default='Média', max_length=10),
        ),
    ]
