# Generated by Django 4.2.27 on 2026-01-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_course_options_course_link_course_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='priority',
            field=models.CharField(choices=[('Estratégica', 'Estratégica'), ('Máxima', 'Máxima'), ('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], default='Média', max_length=15),
        ),
    ]
