# Generated by Django 5.2.10 on 2026-01-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_course_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quantidade_horas',
            field=models.IntegerField(default=0),
        ),
    ]
